spring:
  application:
    name: financial-accounting-app


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/financial-accounting-app
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/financial-accounting-app
    locations: classpath:db/migration
    user: ${MYSQL_USERNAME}
    password:  ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: fin-app