version: '3'
services:
  db:
    image: mysql:latest
    container_name: financial-app
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=financial-accounting-app
#    volumes:
#      - /Users/...:/var/lib/mysql